<a href="https://colab.research.google.com/github/armanjoy09/Image-Processing-Lab/blob/main/Convert_dataset_into_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import numpy as np
from tensorflow.keras.preprocessing import image


In [2]:
# Path to dataset
dataset_path = "/content/drive/MyDrive/CT_Dataset"
classes = ['Bengin cases', 'Malignant cases', 'Normal cases']

In [3]:
# resize size


IMG_SIZE = (128, 128)
data = []
labels = []


In [4]:
for idx, class_name in enumerate(classes):
    class_folder = os.path.join(dataset_path, class_name)
    for img_name in os.listdir(class_folder):
        img_path = os.path.join(class_folder, img_name)


        img = image.load_img(img_path, target_size=IMG_SIZE)   # load & resize

        img_array = image.img_to_array(img) / 255.0            # to numpy + normalize
        data.append(img_array)
        labels.append(idx)


In [5]:
# Convert to numpy arrays
X = np.array(data)
y = np.array(labels)

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (453, 128, 128, 3)
y shape: (453,)


In [6]:
print(X[0])        # See pixel values of first image

[[[0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
  ...
  [0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]]

 [[0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
  ...
  [0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]]

 [[0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
  ...
  [0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]]

 ...

 [[0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
  ...
  [0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]]

 [[0.14901961 0.14901961 0.14901961]
  [0.14901961 0.14901961 0.14901961]
